version: '3.3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: sql_testpassword
    volumes:
      - my-test-db:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
# Names our volume
volumes:
  my-test-db:
